"resources"
{
	//Required Files
	"maps/emp_snowbound_cl6.bsp" "file"
	"maps/emp_snowbound_cl6.res" "file"
	"materials/maps/emp_snowbound_cl6.vmt" "file"
	"materials/maps/emp_snowbound_cl6.vtf" "file"
	"resource/maps/emp_snowbound_cl6.txt" "file"
	//Custom Files
	"materials/water/water_ajacks01.vmt" "file"
	"materials/johnshandy/world/concretewall15_dark.vtf" "file"
	"materials/johnshandy/world/concretewall15_dark.vmt" "file"
	"materials/common/tools/toolscontrolclip .vtf" "file"
	"materials/common/tools/toolscontrolclip .vmt" "file"
	"materials/common/emp_snow/blueice.vtf" "file"
	"materials/common/emp_snow/blueice.vmt" "file"
	"materials/common/jimather/snowsnowwallblend.vmt" "file"
		//BE Missile
	"models/jimather/be_missile.dx80.vtx" "file"
	"models/jimather/be_missile.dx90.vtx" "file"
	"models/jimather/be_missile.mdl" "file"
	"models/jimather/be_missile.phy" "file"
	"models/jimather/be_missile.sw.vtx" "file"
	"models/jimather/be_missile.vvd" "file"
	"materials/common/jimather/be_missile.vtf" "file"
	"materials/common/jimather/be_missile.vmt" "file"
		//NF Missile
	"models/jimather/nf_missile.dx80.vtx" "file"
	"models/jimather/nf_missile.dx90.vtx" "file"
	"models/jimather/nf_missile.mdl" "file"
	"models/jimather/nf_missile.phy" "file"
	"models/jimather/nf_missile.sw.vtx" "file"
	"models/jimather/nf_missile.vvd" "file"
	"materials/common/jimather/nf_missile.vtf" "file"
	"materials/common/jimather/nf_missile.vmt" "file"
		//Nuke Room
	"materials/common/jimather/crosshair.vtf" "file"
	"materials/common/jimather/crosshair.vmt" "file"
	"materials/common/jimather/snowbound_target_map.vtf" "file"
	"materials/common/jimather/snowbound_target_map.vmt" "file"
	"materials/common/jimather/console_00.vtf" "file"
	"materials/common/jimather/console_00.vmt" "file"
	"materials/common/jimather/console_01.vtf" "file"
	"materials/common/jimather/console_01.vmt" "file"
	"materials/common/jimather/console_03.vtf" "file"
	"materials/common/jimather/console_03.vmt" "file"
	"materials/common/jimather/gauge.vtf" "file"
	"materials/common/jimather/gauge.vmt" "file"
	
}
