"Resources"
{
	"maps/emp_fury_rc1.bsp" "file"
	"maps/emp_fury_rc1.res" "file"

	"materials/maps/emp_fury_rc1.vmt" "file"
	"materials/maps/emp_fury_rc1.vtf" "file"

	"materials/flasche/lava/lava.vmt" "file"
	"materials/flasche/lava/lava_basecolor.vtf" "file"
	"materials/flasche/lava/lava_normal.vtf" "file"

	"materials/silk/silk_downfall_moss03arock05c.vmt" "file"
	"materials/silk/silk_downfall_rock04drock05c.vmt" "file"
	"materials/silk/silk_fury_moss03a_grass08d.vmt" "file"
	"materials/silk/silk_fury_moss03a_grass08d_detailtype.vmt" "file"
	"materials/silk/silk_fury_sand01a_grass08d.vmt" "file"

	"materials/silk/silk_grass_08d.vtf" "file"
	"materials/silk/silk_moss_03a.vtf" "file"
	"materials/silk/silk_moss_03b_ssbump.vtf" "file"
	"materials/silk/silk_rock_04d.vtf" "file"
	"materials/silk/silk_rock_04d_ssbump.vtf" "file"
	"materials/silk/silk_rock_05c.vtf" "file"
	"materials/silk/silk_rock_05c_ssbump.vtf" "file"
	"materials/silk/silk_rock_05cb_ssbump.vtf" "file"
	"materials/silk/silk_sand_01_SSBump.vtf" "file"
	"materials/silk/silk_sand_01a.vtf" "file"

	"materials/misfire/tankbarricade_1f2_lg0.vmt" "file"
	"materials/misfire/tankbarricade_1f2_lg1.vmt" "file"
	"materials/misfire/tankbarricade_1f2_lg2.vmt" "file"
	"materials/misfire/tankbarricade_1f2_lg3.vmt" "file"
	"materials/misfire/tankbarricade_1f2_lg4.vmt" "file"
	"materials/misfire/tankbarricade_triangle_2c_lg0.vmt" "file"
	"materials/misfire/tankbarricade_triangle_2c_lg1.vmt" "file"
	"materials/misfire/tankbarricade_triangle_2c_lg2.vmt" "file"
	"materials/misfire/tankbarricade_triangle_2c_lg3.vmt" "file"
	"materials/misfire/tankbarricade_triangle_2c_lg4.vmt" "file"

	"materials/misfire/tankbarricade_1f2_lg0.vtf" "file"
	"materials/misfire/tankbarricade_1f2_lg1.vtf" "file"
	"materials/misfire/tankbarricade_1f2_lg2.vtf" "file"
	"materials/misfire/tankbarricade_1f2_lg3.vtf" "file"
	"materials/misfire/tankbarricade_1f2_lg4.vtf" "file"
	"materials/misfire/tankbarricade_triangle_2c_lg0.vtf" "file"
	"materials/misfire/tankbarricade_triangle_2c_lg1.vtf" "file"
	"materials/misfire/tankbarricade_triangle_2c_lg2.vtf" "file"
	"materials/misfire/tankbarricade_triangle_2c_lg3.vtf" "file"
	"materials/misfire/tankbarricade_triangle_2c_lg4.vtf" "file"

	"models/misfire/tankbarricade_1f2_lg.dx80.vtx" "file"
	"models/misfire/tankbarricade_1f2_lg.dx90.vtx" "file"
	"models/misfire/tankbarricade_1f2_lg.mdl" "file"
	"models/misfire/tankbarricade_1f2_lg.phy" "file"
	"models/misfire/tankbarricade_1f2_lg.sw.vtx" "file"
	"models/misfire/tankbarricade_1f2_lg.vvd" "file"
	"models/misfire/tankbarricade_triangle_2c_lg.dx80.vtx" "file"
	"models/misfire/tankbarricade_triangle_2c_lg.dx90.vtx" "file"
	"models/misfire/tankbarricade_triangle_2c_lg.mdl" "file"
	"models/misfire/tankbarricade_triangle_2c_lg.phy" "file"
	"models/misfire/tankbarricade_triangle_2c_lg.sw.vtx" "file"
	"models/misfire/tankbarricade_triangle_2c_lg.vvd" "file"

	"resource/maps/emp_fury_rc1.txt" "file"
}