"Resources"
{
	"maps/emp_flat_hce" "file"
	"maps/emp_flat_hce" "file"
	"materials/maps/emp_flat.vmt" "file"
	"materials/maps/emp_flat.vtf" "file"
	"materials/silk/silk_blendgrass02grass04.vmt" "file"
	"materials/silk/silk_blendgrass02grass06.vmt" "file"
	"materials/silk/silk_blendgrass02grass07.vmt" "file"
	"materials/silk/silk_blendgrass02rock1.vmt" "file"
	"materials/silk/silk_blendgrass03grass05.vmt" "file"
	"materials/silk/silk_blendgrass03grass07.vmt" "file"
	"materials/silk/silk_blendgrass04grass07.vmt" "file"
	"materials/silk/silk_blendgrass05grass07.vmt" "file"
	"materials/silk/silk_grass02.vtf" "file"
	"materials/silk/silk_grass03.vtf" "file"
	"materials/silk/silk_grass04.vtf" "file"
	"materials/silk/silk_grass05.vtf" "file"
	"materials/silk/silk_grass06.vtf" "file"
	"materials/silk/silk_grass07.vtf" "file"
	"materials/silk/silk_rock1b.vtf" "file"
	"resource/maps/emp_flat.txt" "file"
}
