"Resources"
{
	"maps/emp_hazard_rc6.bsp" "file"
	"maps/emp_hazard_rc6.res" "file"
	"materials/maps/emp_hazard_rc6.vmt" "file"
	"materials/maps/emp_hazard_rc6.vtf" "file"
	"materials/nature/toxicslime002a.vmt" "file"
	"materials/nature/toxicslime002a.vtf" "file"
	"materials/nature/toxicslime002a_beneath.vmt" "file"
	"materials/nature/toxicslime002a_dx70.vmt" "file"
	"materials/nature/toxicslime002a_dx70_beneath.vmt" "file"
	"materials/nature/rockwalldeathvalley.vtf" "file"
	"materials/nature/rockwalldeathvalley_height.vtf" "file"
	"materials/nature/rockwalldeathvalley_normal.vtf" "file"
	"materials/nature/rockwalldeathvalley.vmt" "file"
	"resource/maps/emp_hazard_rc6.txt" "file"
}