"resources"
{
	//map
	"maps/emp_mesa_d6.bsp" "file"
	//download table (this file)
	//"maps/emp_mesa_d6.res" "file"
	//minimap
	"resource/maps/emp_mesa_d6.txt" "file"
	"materials/maps/emp_mesa_d6.vmt" "file"
	"materials/maps/emp_mesa_d6.vtf" "file"
	//custom content
	"materials/mayama/blendmudmud.vmt" "file"
	"materials/mayama/blendmudrock1.vmt" "file"
	"materials/mayama/blendmudrock2.vmt" "file"
	"materials/mayama/blendrockrock1.vmt" "file"
	"materials/mayama/blendrockrock2.vmt" "file"
	"materials/mayama/concretewall15orange.vmt" "file"
	"materials/mayama/crack01.vmt" "file"
	"materials/mayama/dirtmesa1.vmt" "file"
	"materials/mayama/dirtmesa1detail.vmt" "file"
	"materials/mayama/dirtmesa2.vmt" "file"
	"materials/mayama/dirtmesa2detail.vmt" "file"
	"materials/mayama/nf_buildingtexturesfloor02.vmt" "file"
	"materials/mayama/nf_buildingtexturesplate09.vmt" "file"
	"materials/mayama/nf_buildingtexturesplate18.vmt" "file"
	"materials/mayama/nf_buildingtexturesplate19.vmt" "file"
	"materials/mayama/rockmesa3detail.vmt" "file"
	"materials/mayama/Splash01.vmt" "file"
	"materials/mayama/blendrockrock1height.vtf" "file"
	"materials/mayama/concretewall15normal.vtf" "file"
	"materials/mayama/concretewall15orange.vtf" "file"
	"materials/mayama/crack01.vtf" "file"
	"materials/mayama/dirtmesa1.vtf" "file"
	"materials/mayama/dirtmesa1detail.vtf" "file"
	"materials/mayama/dirtmesa1normal.vtf" "file"
	"materials/mayama/dirtmesa2.vtf" "file"
	"materials/mayama/dirtmesa2detail.vtf" "file"
	"materials/mayama/dirtmesa2normal.vtf" "file"
	"materials/mayama/nf_buildingtexturesfloor02.vtf" "file"
	"materials/mayama/nf_buildingtexturesfloor02_normal.vtf" "file"
	"materials/mayama/nf_buildingtexturesplate09.vtf" "file"
	"materials/mayama/nf_buildingtexturesplate09_normal.vtf" "file"
	"materials/mayama/nf_buildingtexturesplate18.vtf" "file"
	"materials/mayama/nf_buildingtexturesplate18_normal.vtf" "file"
	"materials/mayama/nf_buildingtexturesplate19.vtf" "file"
	"materials/mayama/nf_buildingtexturesplate19_normal.vtf" "file"
	"materials/mayama/rockmesa1.vtf" "file"
	"materials/mayama/rockmesa1b.vtf" "file"
	"materials/mayama/rockmesa2.vtf" "file"
	"materials/mayama/rockmesa3detail.vtf" "file"
	"materials/mayama/rockmesa3bdetail.vtf" "file"
	"materials/mayama/rockmesa3normal.vtf" "file"
	"materials/mayama/Splash01.vtf" "file"
	"materials/skybox/mpa28bk.vmt" "file"
	"materials/skybox/mpa28bk.vtf" "file"
	"materials/skybox/mpa28dn.vmt" "file"
	"materials/skybox/mpa28dn.vtf" "file"
	"materials/skybox/mpa28ft.vmt" "file"
	"materials/skybox/mpa28ft.vtf" "file"
	"materials/skybox/mpa28lf.vmt" "file"
	"materials/skybox/mpa28lf.vtf" "file"
	"materials/skybox/mpa28rt.vmt" "file"
	"materials/skybox/mpa28rt.vtf" "file"
	"materials/skybox/mpa28up.vmt" "file"
	"materials/skybox/mpa28up.vtf" "file"
}