"Resources"
{
	"maps/emp_ward_rc2.bsp" "file"
	"maps/emp_ward_rc2.res" "file"
	"materials/maps/emp_ward_rc2.vmt" "file"
	"materials/maps/emp_ward_rc2.vtf" "file"
	"materials/maps/emp_ward/silk_blendsandsand1a.vmt" "file"
	"materials/maps/emp_ward/silk_blendsandsand1b.vmt" "file"
	"materials/maps/emp_ward/silk_blendsandsand2.vmt" "file"
	"materials/maps/emp_ward/silk_blendsandsand3b.vmt" "file"
	"materials/maps/emp_ward/silk_sand1a.vtf" "file"
	"materials/maps/emp_ward/silk_sand1b.vtf" "file"
	"materials/maps/emp_ward/silk_sand2.vtf" "file"
	"materials/maps/emp_ward/silk_sand3b.vtf" "file"
	"resource/maps/emp_ward_rc2.txt" "file"
}