// this file will be overriden. create a seperate file if needed. 
"Resources" 
{
	"models/empfun/platform2b.dx80.vtx"	"file"
	"models/empfun/platform2b.dx90.vtx"	"file"
	"models/empfun/platform2b.mdl"	"file"
	"models/empfun/platform2b.phy"		"file"
	"models/empfun/platform2b.vvd"		"file"
	"models/empfun/platform4b.dx80.vtx"		"file"
	"models/empfun/platform4b.dx90.vtx"		"file"
	"models/empfun/platform4b.mdl"		"file"
	"models/empfun/platform4b.phy"		"file"
	"models/empfun/platform4b.vvd"		"file"
	"models/empfun/platform8b.dx80.vtx"		"file"
	"models/empfun/platform8b.dx90.vtx"		"file"
	"models/empfun/platform8b.mdl"		"file"
	"models/empfun/platform8b.phy"		"file"
	"models/empfun/platform8b.vvd"		"file"
	"models/empfun/cube4.dx80.vtx"		"file"
	"models/empfun/cube4.dx90.vtx"		"file"
	"models/empfun/cube4.mdl"		"file"
	"models/empfun/cube4.phy"		"file"
	"models/empfun/cube4.vvd"		"file"
	"materials/models/empfun/platform.vmt"		"file"
	"materials/models/empfun/platform2.vmt"		"file"
	"materials/models/empfun/platform3.vmt"		"file"
	"materials/models/empfun/platform4.vmt"		"file"
	"materials/models/empfun/platform5.vmt"		"file"
	"materials/models/empfun/platform6.vmt"		"file"
	"materials/models/empfun/platform7.vmt"		"file"
	"materials/models/empfun/platform8.vmt"		"file"
	"materials/models/empfun/platform9.vmt"		"file"
	"materials/models/empfun/platform10.vmt"		"file"
	"materials/models/empfun/platform11.vmt"		"file"
	"materials/models/empfun/platform12.vmt"		"file"
	"materials/models/empfun/platform13.vmt"		"file"
	"materials/models/empfun/platform14.vmt"		"file"
	"materials/models/empfun/platform15.vmt"		"file"
}